### ISSUE TITLE
Applications submitted with 0.6dev12 do not work with 0.6dev14

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#26]
2020-12-08 16:50:06 ERROR LocalSchedulerService:218 - Traceback (most recent call last):
2020-12-08 16:50:06 ERROR LocalSchedulerService:218 -   File "execute_v1.py", line 31, in <module>
2020-12-08 16:50:06 ERROR LocalSchedulerService:218 -     views = controller.list()
2020-12-08 16:50:06 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 537, in list
2020-12-08 16:50:06 ERROR LocalSchedulerService:218 -     return [c.view() for c in self.map.values()]
2020-12-08 16:50:06 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 537, in <listcomp>
2020-12-08 16:50:06 ERROR LocalSchedulerService:218 -     return [c.view() for c in self.map.values()]
2020-12-08 16:50:06 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 109, in view
2020-12-08 16:50:06 ERROR LocalSchedulerService:218 -     return self._view()
2020-12-08 16:50:06 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 345, in _view
2020-12-08 16:50:06 ERROR LocalSchedulerService:218 -     return ComboBoxView(self._id, self.selected, model.titles(), True if self.multiple else None, self.enabled, self.label,
2020-12-08 16:50:06 ERROR LocalSchedulerService:218 - AttributeError: 'ComboBox' object has no attribute 'multiple'
2020-12-08 16:50:17 ERROR LocalSchedulerService:218 - Traceback (most recent call last):
2020-12-08 16:50:17 ERROR LocalSchedulerService:218 -   File "execute_v1.py", line 31, in <module>
2020-12-08 16:50:17 ERROR LocalSchedulerService:218 -     views = controller.list()
2020-12-08 16:50:17 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 537, in list
2020-12-08 16:50:17 ERROR LocalSchedulerService:218 -     return [c.view() for c in self.map.values()]
2020-12-08 16:50:17 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 537, in <listcomp>
2020-12-08 16:50:17 ERROR LocalSchedulerService:218 -     return [c.view() for c in self.map.values()]
2020-12-08 16:50:17 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 109, in view
2020-12-08 16:50:17 ERROR LocalSchedulerService:218 -     return self._view()
2020-12-08 16:50:17 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 345, in _view
2020-12-08 16:50:17 ERROR LocalSchedulerService:218 -     return ComboBoxView(self._id, self.selected, model.titles(), True if self.multiple else None, self.enabled, self.label,
2020-12-08 16:50:17 ERROR LocalSchedulerService:218 - AttributeError: 'ComboBox' object has no attribute 'multiple'
2020-12-08 16:50:38 ERROR LocalSchedulerService:218 - Traceback (most recent call last):
2020-12-08 16:50:38 ERROR LocalSchedulerService:218 -   File "execute_v1.py", line 31, in <module>
2020-12-08 16:50:38 ERROR LocalSchedulerService:218 -     views = controller.list()
2020-12-08 16:50:38 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 537, in list
2020-12-08 16:50:38 ERROR LocalSchedulerService:218 -     return [c.view() for c in self.map.values()]
2020-12-08 16:50:38 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 537, in <listcomp>
2020-12-08 16:50:38 ERROR LocalSchedulerService:218 -     return [c.view() for c in self.map.values()]
2020-12-08 16:50:38 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 109, in view
2020-12-08 16:50:38 ERROR LocalSchedulerService:218 -     return self._view()
2020-12-08 16:50:38 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 345, in _view

2020-12-08 16:50:38 ERROR LocalSchedulerService:218 -     return ComboBoxView(self._id, self.selected, model.titles(), True if self.multiple else None, self.enabled, self.label,
2020-12-08 16:50:38 ERROR LocalSchedulerService:218 - AttributeError: 'ComboBox' object has no attribute 'multiple'
2020-12-08 16:51:21 ERROR LocalSchedulerService:218 - Traceback (most recent call last):
2020-12-08 16:51:21 ERROR LocalSchedulerService:218 -   File "execute_v1.py", line 31, in <module>
2020-12-08 16:51:21 ERROR LocalSchedulerService:218 -     views = controller.list()
2020-12-08 16:51:21 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 537, in list
2020-12-08 16:51:21 ERROR LocalSchedulerService:218 -     return [c.view() for c in self.map.values()]
2020-12-08 16:51:21 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 537, in <listcomp>
2020-12-08 16:51:21 ERROR LocalSchedulerService:218 -     return [c.view() for c in self.map.values()]
2020-12-08 16:51:21 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 109, in view
2020-12-08 16:51:21 ERROR LocalSchedulerService:218 -     return self._view()
2020-12-08 16:51:21 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 195, in _view
2020-12-08 16:51:21 ERROR LocalSchedulerService:218 -     return TextFieldView(self._id, data, True if self.long else None, self.enabled, self.label, self.optional)
2020-12-08 16:51:21 ERROR LocalSchedulerService:218 - AttributeError: 'TextField' object has no attribute 'long'
2020-12-08 16:51:34 ERROR LocalSchedulerService:218 - Traceback (most recent call last):
2020-12-08 16:51:34 ERROR LocalSchedulerService:218 -   File "execute_v1.py", line 31, in <module>
2020-12-08 16:51:34 ERROR LocalSchedulerService:218 -     views = controller.list()
2020-12-08 16:51:34 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 537, in list
2020-12-08 16:51:34 ERROR LocalSchedulerService:218 -     return [c.view() for c in self.map.values()]
2020-12-08 16:51:34 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 537, in <listcomp>
2020-12-08 16:51:34 ERROR LocalSchedulerService:218 -     return [c.view() for c in self.map.values()]
2020-12-08 16:51:34 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 109, in view
2020-12-08 16:51:34 ERROR LocalSchedulerService:218 -     return self._view()
2020-12-08 16:51:34 ERROR LocalSchedulerService:218 -   File "/usr/local/lib/python3.8/site-packages/dstack/controls.py", line 195, in _view
2020-12-08 16:51:34 ERROR LocalSchedulerService:218 -     return TextFieldView(self._id, data, True if self.long else None, self.enabled, self.label, self.optional)
2020-12-08 16:51:34 ERROR LocalSchedulerService:218 - AttributeError: 'TextField' object has no attribute 'long'
