### ISSUE TITLE
The 0.6dev9 doesn't work with Python 3.6

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#15]
```
(dstack_env) D:\ML_projects\dstack_project>dstack
Traceback (most recent call last):
  File "c:\program files\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ML_projects\dstack_project\dstack_env\Scripts\dstack.exe\__main__.py", line 4, in <module>
  File "d:\ml_projects\dstack_project\dstack_env\lib\site-packages\dstack\__init__.py", line 6, in <module>
    from dstack.auto import AutoHandler
  File "d:\ml_projects\dstack_project\dstack_env\lib\site-packages\dstack\auto.py", line 14, in <module>
    from dstack.application.handlers import AppEncoderFactory, AppDecoderFactory
  File "d:\ml_projects\dstack_project\dstack_env\lib\site-packages\dstack\application\__init__.py", line 7, in <module>
    import dstack.application.dependencies as dp
AttributeError: module 'dstack' has no attribute 'application'
```
