### ISSUE TITLE
[Bug]: CLI does not work on Python 3.9 and 3.10

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#2951]
### Steps to reproduce

Run any `dstack` CLI command under Python 3.9 or 3.10

### Actual behaviour

```python
Traceback (most recent call last):
  File "/dstack/venv/bin/dstack", line 10, in <module>
    sys.exit(main())
  File "/dstack/src/dstack/_internal/cli/main.py", line 91, in main
    args.func(args)
  File "/dstack/src/dstack/_internal/cli/commands/apply.py", line 109, in _command
    super()._command(args)
  File "/dstack/src/dstack/_internal/cli/commands/__init__.py", line 68, in _command
    configure_logging()
  File "/dstack/src/dstack/_internal/cli/utils/common.py", line 71, in configure_logging
    level_names = logging.getLevelNamesMapping()
AttributeError: module 'logging' has no attribute 'getLevelNamesMapping'
```

### dstack version

master

### Server logs

```shell

```
