### ISSUE TITLE
[Bug]: Azure provisioning does not work with azure-mgmt-network==28.0.0

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1987]
### Steps to reproduce

1. Install azure-mgmt-network==28.0.0
2. Provision a new Azure instance with dstack
3. You'll see an error in the server logs: `type object 'NetworkManagementClient' has no attribute 'DEFAULT_API_VERSION'`

This is due to a breaking change:

> 28.0.0 (2024-11-01)
This package now only targets the latest Api-Version available on Azure and removes APIs of other Api-Version. After this change, the package can have much smaller size. If your application requires a specific and non-latest Api-Version, it's recommended to pin this package to the previous released version; If your application always only use latest Api-Version, please ingore this change.

It's however unclear how to use Azure API with azure-mgmt-network==28.0.0 since some endpoints require specifying an API version and latest does, e.g.:

https://github.com/dstackai/dstack/blob/7a20386dd3e2d1e448162f093b2cb51392ad909b/src/dstack/_internal/core/backends/azure/compute.py#L509-L512

### dstack version

master
